// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_auth_facebook': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-1:6705390f-d714-49a5-afca-43b348b0c03d',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'coralappv-hosting-mobilehub-1774015819',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2zlsqd3vbtccj.cloudfront.net',
    'aws_facebook_app_id': '447519875768842',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '8c0ab4f94d5e49a0b25b7a0038bec192',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'dc7c945c-45b2-43f3-9344-8c190b0503a4',
    'aws_project_name': 'Coral-App-v1-0',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_name_prefix': 'coralappv-mobilehub-1774015819',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-1_i9puJk1SO',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1gggqfvjeked46av0o5ssaebvv',
}

export default awsmobile;
